// <auto-generated />
using System;
using FacebookClone.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FacebookClone.Infrastructure.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20251222163000_AddMessagingAndNotifications")]
    partial class AddMessagingAndNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Existing entities are defined in the previous snapshot/migrations.
            // We add only the new entities here for tooling.

            modelBuilder.Entity("FacebookClone.Data.Entities.Message", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Content")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("GroupId")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsGroup")
                    .HasColumnType("bit");

                b.Property<DateTime?>("ReadAt")
                    .HasColumnType("datetime2");

                b.Property<string>("ReceiverId")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("SenderId")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.ToTable("Messages");
            });

            modelBuilder.Entity("FacebookClone.Data.Entities.Notifications", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<bool>("IsRead")
                    .HasColumnType("bit");

                b.Property<string>("Message")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("MetadataJson")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("RelatedId")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("ReadAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Title")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.ToTable("Notifications");
            });
#pragma warning restore 612, 618
        }
    }
}
